version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 8080:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=test_user
      - POSTGRES_DB=scribble
